### ISSUE TITLE
invalid link of A pre-trained Keras appearance model based on ResNet50 

### ISSUE THREAD

**Issue by MOONBEAR0703** [ergysr/DeepCC#1]
Hello. The link of weights you have provided in the Appearance model is an invalid one.[https://github.com/ergysr/DeepCC#appearance-model](url)
weights:[http://vision.cs.duke.edu/DukeMTMC/data/misc/matlab-weights.hdf5](url)

**Comment by ergysr** [comment]
@MOONBEAR0703 I am still in the process of integrating my training code with Matlab. There will be a status update once the code is uploaded.

**Comment by MOONBEAR0703** [comment]
@ergysr hi,have you finished updating your entire code?

**Comment by ergysr** [comment]
@MOONBEAR0703 I just did. Let me know if there's still an issue.
