### ISSUE TITLE
Compile mex file

### ISSUE THREAD

**Issue by MOONBEAR0703** [ergysr/DeepCC#10]
[https://github.com/ergysr/DeepCC#compiling](url) I have installed mexopencv and gurobi in ubuntu16.04.
And I run compile in matlab.But it didn't do mex.
`In file included from
/media/lab324/sdc1/xy/DeepCC/src/correlation_clustering/external/KL/andres/graph/graph.hxx:17:0,
                 from
                /media/lab324/sdc1/xy/DeepCC/src/correlation_clustering/external/KL/Multicut_KL_MEX.cpp:3:
                 /media/lab324/sdc1/xy/DeepCC/src/correlation_clustering/external/KL/andres/graph/detail/graph.hxx:6:40:
                 fatal error: andres/random-access-set.hxx: no that file or directories
 #include "andres/random-access-set.hxx"
                                        ^
compilation terminated.

wrong compile (line 5)
mex -O -largeArrayDims Multicut_KL_MEX.cpp
 `

**Comment by ergysr** [comment]
Turned out to be a g++ issue. This [change](https://github.com/ergysr/DeepCC/commit/5dfe95a91f694cdfd08b643fe355d1c1e41e461d) fixes it.
