### ISSUE TITLE
File Not Found: omp.h

### ISSUE THREAD

**Issue by connorgoggins** [ergysr/DeepCC#13]
Hi! Really excited by this repository and trying to get it running on my MacBook Pro (High Sierra), but running into a bug when I try to compile to obtain mex files for the solver/helper functions. Here is the error when I run `compile.m` in MATLAB:

```Error using mex
/Users/connorgoggins/Documents/mydir/DeepCC/src/external/motchallenge-devkit/utils/clearMOTMex.cpp:4:10:
fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
```

Any suggestions? Thanks so much!

**Comment by ergysr** [comment]
Hi Connor. It looks like the C++ configured with Matlab cannot find the OpenMP library. Would any of [these](https://stackoverflow.com/questions/35134681/installing-openmp-on-mac-os-x-10-11/35467142) solve your issue?
