### ISSUE TITLE
detections

### ISSUE THREAD

**Issue by MOONBEAR0703** [ergysr/DeepCC#14]
https://github.com/ergysr/DeepCC#training-an-appearance-model
> You can also use `features = embed_detections(opts, detections); `to compute features for a set of detections in the format [camera, frame, left, top, width, height];

When I typed `features = embed_detections(opts, detections); `, it said 

> Undefined functions or variables of 'detections'

.

**Comment by ergysr** [comment]
I think you didn't provide any detections to the function. See [compute_L0_features(opts)](https://github.com/ergysr/DeepCC/blob/a17957703df6ad0a23bd6692a34163242e8c5fe6/src/compute_L0_features.m#L20) for an example.

**Comment by MOONBEAR0703** [comment]
You mean that I can add  

>  for iCam = 1:opts.num_cam
    
    % Load poses
    load(fullfile(opts.dataset_path, 'detections','openpose', sprintf('camera%d.mat',iCam)));
    poses = detections;
    
    % Convert poses to detections
    detections = zeros(size(poses,1),6);
    for k = 1:size(poses,1)
        pose = poses(k,3:end);
        bb = pose2bb(pose, opts.render_threshold);
        [newbb, newpose] = scale_bb(bb,pose,1.25);
        detections(k,:) = [iCam, poses(k,2), newbb];
    end
end

to `embed_detections.m` to provide detections?

In fact, I am a little confused about the order of the scripts, in other words, for `L3 + appearance model` and `First working demo`, do you mean that I need to fun `First working demo` first? Now I just follow the steps you have provided in the `readme.md` to train appearance model.

**Comment by ergysr** [comment]
As the readme implies, this helper function is optional, so for now you can ignore it. You can use it later if you wish to substitute the L0 features with your own.
If you have already trained the appearance model simply run `demo`.

**Comment by MOONBEAR0703** [comment]
Thanks~
