### ISSUE TITLE
L0_features

### ISSUE THREAD

**Issue by MOONBEAR0703** [ergysr/DeepCC#15]
Hi @ergysr What's the use of L0_features? It seems that I didn't use the pre-computed features of L0.

**Comment by ergysr** [comment]
L0_features represent the appearance descriptors of the input detections. These are loaded during L1 when associating detections into tracklets. Specifically here:

https://github.com/ergysr/DeepCC/blob/2fde99d04410a8ef1ed7358be20f5329b2edd9c7/src/compute_L1_tracklets.m#L16

You can either download the features that we provide, or compute them yourself with your own model. If no features exist in the L0 features folder, running the demo code will raise an error.

**Comment by MOONBEAR0703** [comment]
Thanks. I have run demo successfully.  Maybe I mixed up paths before but somehow it didn't matter.

**Comment by ergysr** [comment]
That's great. So you likely download the pre-computed features as the README suggests.
