### ISSUE TITLE
DeepCC demo failure

### ISSUE THREAD

**Issue by SamvitJ** [ergysr/DeepCC#18]
After successfully computing tracklets and single-camera trajectories, the demo halts on multi-cam trajectories with the following error. The error seems to indicate that the feature files are missing on disk, but I have downloaded these, as per the install instructions:
```
root@ip-172-31-10-163:/ebs/DeepCC# ls experiments/demo/L0-features/
features1.h5  features2.h5  features3.h5  features4.h5  features5.h5  features6.h5  features7.h5  features8.h5
```

The error:
```
...
cam8_trainval_mini
 IDF1  IDP  IDR| Rcll  Prcn   FAR|   GT  MT   PT   ML|    FP    FN   IDs    FM|  MOTA  MOTP MOTAL 
 77.9 80.0 75.9| 88.7  93.5  0.20|  241 218   12   11| 11737 21265    20    72|  82.5  76.6  82.5 


 ********************* Your DukeMTMCT Results *********************
 IDF1  IDP  IDR| Rcll  Prcn   FAR|   GT  MT   PT   ML|    FP    FN   IDs    FM|  MOTA  MOTP MOTAL 
 85.3 85.4 85.1| 93.2  93.5  0.16| 14891363   92   34| 77366 80988   171   454|  86.7  78.5  86.7 

 ********************* Your DukeMTMCT MultiCam Results *********************
IDF1   IDP    IDR
26.72  26.76  26.68
Extracting images for trajectory 1/1635

Error using fprintf
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in getTrajectoryFeatures (line 37)
            fprintf(fid,'%05d,%s\n',k,filename);

Error in compute_L3_identities (line 5)
trajectories = getTrajectoryFeatures(opts, trajectories);

Error in demo (line 29)
compute_L3_identities(opts);

Error in run (line 91)
evalin('caller', strcat(script, ';'));
```

As a side point, the F1/P/R numbers under "Your DukeMTMCT MultiCam Results" seem too low (26.72  26.76  26.68). Are these the expected values?

**Comment by SamvitJ** [comment]
The error is on line 37 of getTrajectoryFeatures.m:
```
fprintf(fid,'%05d,%s\n',k,filename);
```
The error message suggests that `fid` is invalid. `fid` should be initialized by lines 5-13:
```
csvfile = sprintf('%s/%s/L3-identities/temp_images/L2images.csv',opts.experiment_root, opts.experiment_name);

if opts.identities.extract_images
    temp_dir = sprintf('%s/%s/L3-identities/temp_images_%s',opts.experiment_root, opts.experiment_name, opts.sequence_names{opts.sequence});
    status = rmdir(temp_dir,'s');
    mkdir(temp_dir);
    fid = fopen(csvfile,'w');
end
```
unless csvfile is not present. Checking the disk:
```
root@ip-172-31-10-163:/ebs/DeepCC# ls experiments/demo/L3-identities/temp_images/
ls: cannot access 'experiments/demo/L3-identities/temp_images/': No such file or directory
```
it is indeed the case that the entire parent directory is missing.

Is this a file we can download from somewhere, or was it supposed to be generated by a previous step? (There were no error messages previously, so I don't think it can be the latter.)

**Comment by SamvitJ** [comment]
I'm able to get past the error on this line by manually creating the parent directory:
```
mkdir experiments/demo/L3-identities/temp_images/
```
Should this be added to the script?

**Comment by ergysr** [comment]
Thanks for pointing the discrepancy in the code. I have added a [fix](https://github.com/ergysr/DeepCC/commit/0ad6f2adbc0796614b06d4fadab2b8ebfa437e39). Please update to the latest version. Essentially the temp folder should always be in the format 'temp_images_<sequence_name>'.

> As a side point, the F1/P/R numbers under "Your DukeMTMCT MultiCam Results" seem too low (26.72 26.76 26.68). Are these the expected values?

Yes, the multi-camera score is not expected to be high right after computing single-camera trajectories. The next step (L3) does across camera association, and you would expect something like:

```
 ********************* Your DukeMTMCT Results *********************
 IDF1  IDP  IDR| Rcll  Prcn   FAR|   GT  MT   PT   ML|    FP    FN   IDs    FM|  MOTA  MOTP MOTAL 
 85.3 85.4 85.1| 93.2  93.5  0.16| 14891363   92   34| 77366 80988   171   454|  86.7  78.5  86.7 

 ********************* Your DukeMTMCT MultiCam Results *********************
IDF1   IDP    IDR
80.33  80.45  80.21
```

**Comment by SamvitJ** [comment]
To run L3 of the demo, do we need to train and evaluate the appearance model? Asking because after the image extraction completes, I run into the following error:
```
Extracting imgages for trajectory 1634/1635
Extracting imgages for trajectory 1635/1635
python embed.py --experiment_root experiments/demo_weighted_triplet --image_root /ebs/DeepCC --filename L2features_trainval_mini.h5 --dataset ../../experiments/demo/L3-identities/temp_images/L2images.csv  File "embed.py", line 223
    flush=True, end='')
         ^
SyntaxError: invalid syntax
Error using movefile
mv: cannot stat
'/ebs/DeepCC/src/triplet-reid/experiments/demo_weighted_triplet/L2features_trainval_mini.h5':
No such file or directory

Error in getTrajectoryFeatures (line 61)
movefile(sprintf('src/triplet-reid/%s/L2features_%s.h5',opts.net.experiment_root,
opts.sequence_names{opts.sequence}),featuresfile);

Error in compute_L3_identities (line 5)
trajectories = getTrajectoryFeatures(opts, trajectories);

Error in run (line 91)
evalin('caller', strcat(script, ';'));
```

**Comment by MOONBEAR0703** [comment]
@SamvitJ Maybe you should run `embed(opts);` after you train the appearance model. I have reproduced the results.

**Comment by ergysr** [comment]
@SamvitJ Yes, a trained model is necessary for step L3 of the demo.

@MOONBEAR0703 L3 features are computed here: 
https://github.com/ergysr/DeepCC/blob/master/src/L3-identities/getTrajectoryFeatures.m#L51-L64 

`L2features_test_easy.h5` is first created in `demo_weighted_triplet`, then it is moved to `L3-identitities`.

**Comment by MOONBEAR0703** [comment]
@ergysr If I want to get a tracker result of the test_easy video, I don't need to train an appearance model because I have trained it before, is it right?

**Comment by ergysr** [comment]
@MOONBEAR0703 Right.

**Comment by MOONBEAR0703** [comment]
Maybe it is the Python edition problem. We need Python3. @SamvitJ

**Comment by ergysr** [comment]
Python3 is necessary. I will mark this in the readme.

**Comment by MOONBEAR0703** [comment]
https://github.com/ergysr/DeepCC/blob/3654685dd949fa596a9e2d0e439aea53f0fc59a9/src/L3-identities/getTrajectoryFeatures.m#L53 You can also change it to 

> command = strcat('python3 embed.py' , ...

Because sometimes the system's default is Python2.

**Comment by MOONBEAR0703** [comment]
@ergysr    Can you provide us the groundtruth of `test_easy` and `test_hard` ?

**Comment by ergysr** [comment]
@MOONBEAR0703 I have made an update [here](https://github.com/ergysr/DeepCC/commit/819dae07c31e683e5009b90cb7e76e6a75531ae1). You can now set your python3 command in `get_opts.m`.
