### ISSUE TITLE
Stuck at demo.m

### ISSUE THREAD

**Issue by Miranda84315** [ergysr/DeepCC#21]
Hello~
When I am running `demo.m`
And I got stuck about 4 hours until now....
This is the last message 

> Cam: 8 - Window 140655...140955
merging tracklets in appearance group 1
30
435
Saving results
Sequences: 
    'cam1_trainval_mini'
    'cam2_trainval_mini'
    'cam3_trainval_mini'
    'cam4_trainval_mini'
    'cam5_trainval_mini'
    'cam6_trainval_mini'
    'cam7_trainval_mini'
    'cam8_trainval_mini'
... (skip)
 ********************* Your DukeMTMCT Results *********************
 IDF1  IDP  IDR| Rcll  Prcn   FAR|   GT  MT   PT   ML|    FP    FN   IDs    FM|  MOTA  MOTP MOTAL 
 85.0 85.2 84.9| 93.2  93.5  0.16| 14891364   92   33| 77756 81421   179   460|  86.6  78.5  86.7 
 ********************* Your DukeMTMCT MultiCam Results *********************
IDF1   IDP    IDR
26.92  26.96  26.88
Extracting imgages for trajectory 1/1634

It stops at `Extracting imgages for trajectory 1/1634` for many hours
Then it didn't run any other messages.....
Is that always taking  so long
Or is something wrong ?

Because I don't use Gurobi
So I change the line 21 `opts.optimization = 'BIPCC'` to  `opts.optimization = 'KL';`
Is that the problem ?

**Comment by ergysr** [comment]
This is not normal behavior, and it is not related to the optimization method. 

Does something as simple as the following work?
```
opts = get_opts();
img = opts.reader.getFrame(1,1);
imshow(img);
```
If the issue is not the video reader path you can run `compute_L3_identities(opts);` while having placed breakpoints in `src/L3-identities/getTrajectoryFeatures.m`.

**Comment by Miranda84315** [comment]
Thank you !
I knew where is the problem, it is because the path `opts.dataset_path = 'F:/DukeMTMC/';` 
But I used  `opts.dataset_path = 'F:/DukeMTMC';` , is lack of "/" 
and it can work after I add "/" to the path.
