### ISSUE TITLE
'args.json' could not be found

### ISSUE THREAD

**Issue by chaoma99** [ergysr/DeepCC#22]
Good job and thanks for sharing the code. 

However, when I run demo.m, it says that the 'args.json' could not be found. 
Can you please help me out?

**Comment by ergysr** [comment]
This could be because the demo can't find the trained appearance model. Have you run the appearance training code from the readme before running the demo?

**Comment by chaoma99** [comment]
Hi Ergysr, thanks for your reply. I follow your instruction to train the model. I indeed found the args.json file. However, there is another problem to run the training code. It seems that the checkpoint file does not match. By the way, I download the resnet_v1_50.ckpt file following your suggested link. 

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Tensor name "emb/biases" not found in checkpoint files experiments/demo_weighted_triplet/resnet_v1_50.ckpt
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[Node: save/RestoreV2/_301 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_306_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by ergysr** [comment]
I think you downloaded the checkpoint file to the wrong folder.

> download resnet_v1_50.ckpt in src/triplet-reid/

**Comment by chaoma99** [comment]
Many thanks. The problem is caused by an empty h5 file stored in the last failed experiment. I deleted all the generated files and can run it now.  Thanks again. Will close this comment.
