### ISSUE TITLE
train_duke using hard identity pool

### ISSUE THREAD

**Issue by Miranda84315** [ergysr/DeepCC#25]
Hello,
I want to use your code with hard identity pool,
and implement your paper "Features for Multi-Target Multi-Camera Tracking and Re-Identification"
> The hard identity pool size H is set to 50

because the original code `net.hard_pool_size = 0;`
so I change `get_opts.m` line 91 `net.hard_pool_size = 50;`
but when I run the `train_duke(opts);`
I got this error below

> Reference to non-existent field 'train_embeddings'.
Error in train_duke (line 34)
    command = [command, ' --train_embeddings ', net.train_embeddings]; 

and check the `get_opts.m`, there don't have the `train_embeddings`
also saw the `train.py` line 155

> help='Path to pre-computed features of training set to be used for the hard identity pool'

but I still not sure how to setting the train_embeddings parameter

**Comment by ergysr** [comment]
Simply run `train_duke_hnm` to train with hard negative mining.

**Comment by Miranda84315** [comment]
thank you very much for your help!
