### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by kingwmk** [ergysr/DeepCC#26]
I got a mistake when compile：
错误使用 mex
/home/wangmingkun/code/DeepCC-master/src/external/motchallenge-devkit/utils/MinCostMatching.cpp: 在函数‘double
MinCostMatching(const VVD&, VI&, VI&)’中:
/home/wangmingkun/code/DeepCC-master/src/external/motchallenge-devkit/utils/MinCostMatching.cpp:50:37: 错
误：‘fabs’在此作用域中尚未声明
    if (fabs(cost[i][j] - u[i] - v[j]) < 1e-10) {
                                     ^

出错 compile (line 19)
mex utils/MinCostMatching.cpp -outdir utils CXXFLAGS="$CXXFLAGS --std=c++11".
It says that the wrong use of mex. Error: ‘fabs’ has not been declared in this scope.
May i ask how can i solve it.

**Comment by kingwmk** [comment]
i am sorry to bother, and i solve it by adding "#include <math.h>" in the MinCostMatching.cpp file.Thanks !!

**Comment by UranusWang** [comment]
> i am sorry to bother, and i solve it by adding "#include <math.h>" in the MinCostMatching.cpp file.Thanks !!

Thank you.That solved my issue too.
