### ISSUE TITLE
videocapture read in empty

### ISSUE THREAD

**Issue by yuyuwang** [ergysr/DeepCC#28]
hello
When i'm running demo.m,i got a stuck same to #21 
Then i tied 
```
opts = get_opts();
img = opts.reader.getFrame(1,1);
imshow(img);
```
The program did not report an error.
But I found `img`  is an empty matrix.

And,the value of variable in `obj.Video` are 0 besides `obj.Video.id`
```
obj.Video = cv.VideoCapture(sprintf('%svideos/camera%d/%05d.MTS',obj.DatasetPath,obj.CurrentCamera, obj.CurrentPart));
```
Is the problem in compiling opencv or mexopencv？

**Comment by ergysr** [comment]
I have not encountered this before so I am not sure. Are you able to read images with the [Matlab VideoReader](https://www.mathworks.com/help/matlab/ref/videoreader.html) instead?

**Comment by yuyuwang** [comment]
I can use `Matlab VideoReader` to read in mp4 files,but for MTS, program error is
```
Error using VideoReader/init (line 619)
Could not read file due to an unexpected error. Reason: Unable to initialize the video obtain properties

Error in VideoReader (line 172)
            obj.init(fileName);
```

**Comment by yuyuwang** [comment]
My opencv didn't compile with ffmpeg support ....
