### ISSUE TITLE
Can i use my own videos for test ?

### ISSUE THREAD

**Issue by Qidian213** [ergysr/DeepCC#29]
Thanks!

**Comment by ergysr** [comment]
Yes, though you would need to write your own VideoReader.

**Comment by Qidian213** [comment]
Can it run on ubuntu16.04 system ?  And this project can run on any number cameras (like 1,2,3,4 ...) with DukeMTMC benchmarks or my own videos ? From the code ,it seems that i can do it by change cameras number . Thanks !

**Comment by ergysr** [comment]
It should, maybe with few tweaks.

**Comment by Qidian213** [comment]
I found that when test on test-easy dataset , it can not generate result video with `render_trajectories_top`, like test on train_mini dataset it need trainval.mat file . but we do not have test_easy.mat . it is right ?

**Comment by ergysr** [comment]
Result low: see this https://github.com/ergysr/DeepCC/issues/18#issuecomment-418414943
startFrame, endFrame: I have missed adding them, you can manually set them.
test_easy.mat: yes, it is not publicly available
