### ISSUE TITLE
train_duke(opts) AttributeError: 'list' object has no attribute 'get_shape'

### ISSUE THREAD

**Issue by wildcat5566** [ergysr/DeepCC#33]
Hi!

I am currently working on the "training an appearance model" section.
However when I run 

> train_duke(opts) 

I get following: 
AttributeError: 'list' object has no attribute 'get_shape'

Following is the full error messages.
Thank you for your help!

> opts = get_opts()

opts = 

  struct with fields:

                 dataset_path: '/data/dukeMTMC'
                  gurobi_path: 'C:/gurobi800/win64/matlab'
              experiment_root: 'experiments'
              experiment_name: 'demo'
                      python3: 'python3'
                       reader: [1×1 DukeVideoReader]
                     eval_dir: 'L3-identities'
                    visualize: 0
                  image_width: 1920
                 image_height: 1080
               current_camera: -1
                        world: 0
                         ROIs: {1×8 cell}
    minimum_trajectory_length: 100
                 optimization: 'BIPCC'
                use_groupping: 1
                      num_cam: 8
                     sequence: 2
               sequence_names: {1×4 cell}
           sequence_intervals: {1×4 cell}
                 start_frames: [5543 3607 27244 31182 1 22402 18968 46766]
             render_threshold: 0.0500
               load_tracklets: 1
            load_trajectories: 1
                    tracklets: [1×1 struct]
                 trajectories: [1×1 struct]
                   identities: [1×1 struct]
                          net: [1×1 struct]

> train_duke(opts)
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
[0m2018-10-26 17:31:53,706 [INFO] train: Training using the following parameters:[0m
[0m2018-10-26 17:31:53,706 [INFO] train: augment: True[0m
[0m2018-10-26 17:31:53,706 [INFO] train: batch_k: 4[0m
[0m2018-10-26 17:31:53,706 [INFO] train: batch_p: 18[0m
[0m2018-10-26 17:31:53,707 [INFO] train: checkpoint_frequency: 1000[0m
[0m2018-10-26 17:31:53,707 [INFO] train: crop_augment: False[0m
[0m2018-10-26 17:31:53,707 [INFO] train: decay_start_iteration: 15000[0m
[0m2018-10-26 17:31:53,707 [INFO] train: detailed_logs: False[0m
[0m2018-10-26 17:31:53,707 [INFO] train: embedding_dim: 128[0m
[0m2018-10-26 17:31:53,707 [INFO] train: experiment_root: experiments/demo_weighted_triplet[0m
[0m2018-10-26 17:31:53,707 [INFO] train: flip_augment: False[0m
[0m2018-10-26 17:31:53,707 [INFO] train: hard_pool_size: 0[0m
[0m2018-10-26 17:31:53,708 [INFO] train: head_name: fc1024[0m
[0m2018-10-26 17:31:53,708 [INFO] train: image_root: /data/dukeMTMC/DukeMTMC-reID[0m
[0m2018-10-26 17:31:53,708 [INFO] train: initial_checkpoint: resnet_v1_50.ckpt[0m
[0m2018-10-26 17:31:53,708 [INFO] train: learning_rate: 0.0003[0m
[0m2018-10-26 17:31:53,708 [INFO] train: loading_threads: 8[0m
[0m2018-10-26 17:31:53,709 [INFO] train: loss: weighted_triplet[0m
[0m2018-10-26 17:31:53,709 [INFO] train: margin: soft[0m
[0m2018-10-26 17:31:53,709 [INFO] train: metric: euclidean[0m
[0m2018-10-26 17:31:53,709 [INFO] train: model_name: resnet_v1_50[0m
[0m2018-10-26 17:31:53,709 [INFO] train: net_input_height: 256[0m
[0m2018-10-26 17:31:53,710 [INFO] train: net_input_width: 128[0m
[0m2018-10-26 17:31:53,710 [INFO] train: pre_crop_height: 288[0m
[0m2018-10-26 17:31:53,710 [INFO] train: pre_crop_width: 144[0m
[0m2018-10-26 17:31:53,710 [INFO] train: resume: False[0m
[0m2018-10-26 17:31:53,710 [INFO] train: train_embeddings: None[0m
[0m2018-10-26 17:31:53,711 [INFO] train: train_iterations: 25000[0m
[0m2018-10-26 17:31:53,711 [INFO] train: train_set: data/duke_train.csv[0m
Traceback (most recent call last):
  File "train.py", line 586, in <module>
    main()
  File "train.py", line 415, in main
    lambda im, fid, pid: (tf.py_func(augment_images, [im],[tf.float32]), fid, pid))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 790, in map
    return MapDataset(self, map_func)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1597, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/function.py", line 486, in add_to_graph
    self._create_definition_if_needed()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/function.py", line 321, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/function.py", line 338, in _create_definition_if_needed_impl
    outputs = self._func(*inputs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1585, in tf_map_func
    ret, [t.get_shape() for t in nest.flatten(ret)])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1585, in <listcomp>
    ret, [t.get_shape() for t in nest.flatten(ret)])
AttributeError: 'list' object has no attribute 'get_shape'

**Comment by ergysr** [comment]
You can refer to the solution in [#12](https://github.com/ergysr/DeepCC/issues/12#issuecomment-414677362). Let me know if that doesn't solve it for you.

**Comment by wildcat5566** [comment]
Dear Ergys:

According to issue #12,

Replacing Line 26 in DeepCC/src/triplet-reid/train.py

>     command = [command, ' --augment'];

with

> command = [command, ' --flip_augment --crop_augment'];

Helped me get rid of the error.
Thank you so much Ergys! Have a nice day.
