### ISSUE TITLE
Can't render visualization result of my own result

### ISSUE THREAD

**Issue by ho1messi** [ergysr/DeepCC#34]
I set the sequence to "test_easy" and get the result in L3-identities. But in render_trajectories_top.m, it load the ground truth trainval.mat directly. 

In L3-identities, there are not *.mat files like trainval.mat, so how can I just render the result of my own?

**Comment by ergysr** [comment]
You will need to modify the script to load your L3 trajectories instead of the ground truth trajectories. 

You need to read your output files one by one with `dlmread`, concatenate the the data into the variable `trajectories`, and run the rest of the script `render_trajectories_top`.

**Comment by ho1messi** [comment]
It works, thank you!
