### ISSUE TITLE
ffmpeg.exe absent

### ISSUE THREAD

**Issue by wildcat5566** [ergysr/DeepCC#36]
Hello again

I was trying to extract frames from all .MTS video files
However the line here indicates requirement of "ffmpeg.exe" which happens to be absent and I have no idea where the path should be set to.

https://github.com/ergysr/DeepCC/blob/master/src/duke/downloadDukeMTMC.m#L145

Thank you very much for your help.

**Comment by ergysr** [comment]
ffmpeg is an external tool. If it is not installed in your system you can download it from https://www.ffmpeg.org/

**Comment by wildcat5566** [comment]
Okay thank you I just finished the installation. Didn't know about that at the beginning.
