### ISSUE TITLE
How can it be used in commercial purposes?

### ISSUE THREAD

**Issue by IlyaGulya** [ergysr/DeepCC#37]
Hello!
I've found that license does not allow to use this project with commercial purposes.
It is not possible at all or there is any way to make it possible?
Buy a license, for example.

**Comment by ergysr** [comment]
In principle it is possible. You can direct your licensing questions to the [Duke Office of Licensing](https://olv.duke.edu/contact/) and they will be able to provide more details.

**Comment by IlyaGulya** [comment]
Thanks!
