### ISSUE TITLE
Can I run `demo` without having trained an appearance model first?

### ISSUE THREAD

**Issue by BadWindshield** [ergysr/DeepCC#41]
Sorry for the newbie question.

**Comment by ergysr** [comment]
You can only run the single-camera tracking part of the demo without an appearance model. For the multi-camera part you would need to train first.

**Comment by BadWindshield** [comment]
I see. Thanks!

I am currently training an appearance model. It is running (w/o a GPU), but it is slow (at about 1 iteration per minute). Since we need to run 25k iterations, it can take 2-3 weeks. What kind of a speed up would I get if I use a GPU? 50x?

**Comment by ergysr** [comment]
1 iteration takes between 0.5 and 1 second, so overall training lasts few hours.

**Comment by BadWindshield** [comment]
Thanks.

**Comment by ortegatron** [comment]
Its taking long time for me too, Im running without GPU, that 0.5 second time is on CPU or GPU?
It might also be i'm reading the images from a hard disk...

**Comment by ergysr** [comment]
0.5 seconds per iteration on the GPU (reading images from the hard disk). I never tried with the CPU only, but I assume it might take a week and it's not worth it.

**Comment by ortegatron** [comment]
Yep, I'm trying to run it on a amazon EC2. Should I upload the resulted trained model here so anyone who needs it can download it?
