### ISSUE TITLE
Ground Truth Visualization

### ISSUE THREAD

**Issue by xuehaouwa** [ergysr/DeepCC#42]
Hi,

Currently, I am trying to render trajectories on videos. I used both trainvalRAW.mat and trainval.mat to get ground truth data. However, as shown in the figure, visualization results of some trajectories are a little 'offset'.
![screenshot from 2018-11-20 14-31-03](https://user-images.githubusercontent.com/26236658/48755765-7e889380-ecd1-11e8-9010-b56c429c86c4.png)

Does anyone have the same problem?

Thanks!

**Comment by ergysr** [comment]
What is the percentage of such cases? It's likely from interpolation as the ground truth was annotated every few frames.

**Comment by xuehaouwa** [comment]
> What is the percentage of such cases? It's likely from interpolation as the ground truth was annotated every few frames.

Only a few trajectories in each camera videos. Not too much. Maybe it's because of the interpolation. Thank you for your reply.
