### ISSUE TITLE
About real-time

### ISSUE THREAD

**Issue by RandomFool123** [ergysr/DeepCC#44]
From the results of the experiment, the effect is very good.Is your method suitable for real-time multi-camera multi-target tracking?

**Comment by RandomFool123** [comment]
Hello. Because the DeepCC described in your paper has achieved near real-time performance, I am very curious as to whether he also performs well in crowded public places such as stations or airports, assuming about 4 to 8 cameras, each camera contains About 30 people, the program runs on the TESLA P100. How does DeepCC perform in this situation?

**Comment by ergysr** [comment]
We have only tested DeepCC on existing datasets. If you know of other large scale multi-camera sequences, feel free to share them! The best is to try the code for yourself, and draw your own conclusions.

For offline use, this code took less than 1 day to process the entire Duke sequence, e.g. detections, features, tracking. The cumulative length of the sequences is about 24 hours. With other optimizations and parallelism the runtime can be reduced, and how to exactly do this remains an open question. 

For online use, and assuming the detector is not the computational bottleneck, the tracker can run at 30 fps on average. You can also set a timeout to the gurobi solver, e.g. 5 seconds, so you don't get delays. Or you can use one of the other solvers for higher processing speed, but you might be loosing on accuracy.
