### ISSUE TITLE
train_duke(opts);

### ISSUE THREAD

**Issue by MOONBEAR0703** [ergysr/DeepCC#45]
hi,Ergysr! Have you ever met such error? When I run `train_duke(opts);`,it shows:

> python3: symbol lookup error: python3: undefined symbol: XML_SetHashSalt

**Comment by ergysr** [comment]
I have not, and the issue doesn't seem to be related to this code, rather to the configuration of libraries in the machine.

**Comment by MOONBEAR0703** [comment]
I tried to run train_duke.sh in the terminal, it works. But its gpu_device is default 0, I tried to add 

> import os

> os.environ['CUDA_VISIBLE_DEVICES']='2'

But it is still running at gpu 0.
