### ISSUE TITLE
Openpose detection

### ISSUE THREAD

**Issue by RandomFool123** [ergysr/DeepCC#47]
Why do you use openpose to detect effects so well? I use the officially trained body_25 and coco models, but the effect is not very good, especially when the two people are overlapped, the occluded people can hardly detect it. Do you specifically train an openpose model on the duke video, or do you have other optimization methods?

**Comment by ergysr** [comment]
I used the default coco model, however I set `--net_resolution` to around 1920x1080 to improve the quality of the detections.

**Comment by RandomFool123** [comment]
Thank you very much. I reset the value of --net_resolution according to your method, and the effect is better.
