### ISSUE TITLE
[question] - generate more metadata/combination with densenet and facenet

### ISSUE THREAD

**Issue by archenroot** [ergysr/DeepCC#51]
Imagine you track someone who trows away his jacket and/or throwers :-), have you tested such scenario, or all objects are still "same" across all cameras?

I was thinking about combination of:
- https://github.com/ZhaoJ9014/Multi-Human-Parsing_MHP
- or https://github.com/ashafaei/dense-depth-body-parts
with facenet and densenet (extended to calculate height and weight of an object)

I think I can combine them by running independently and let combine those on separate layer, or any idea about future extensions?

**Comment by ergysr** [comment]
There are few such scenarios in the dataset, one shown in the CVPR paper in Fig 7. The worker takes off his jacket at some point, and shows up in Cam 5 without wearing the jacket. I haven't inspected in detail what happens at that instant, it all depends what the correlation score of appearance features is (the motion correlation should be positive). Your ideas are perfectly valid and are likely going to improve performance. However if you focus on applying semantic parsing for these cases (which are limited in existing data) the scores might not improve that much. This shouldn't stop you from trying, research is not just about scores :)

In my view what remains challenging in MTMCT and ReID are crowded scenes, e.g. the test-hard sequence. There you get to observe people for short periods of time and mostly their upper body. If you could leverage your parsing ideas for crowds, and re-identify people in other views using limited observations but improved appearance descriptors, your ideas will be more tangible.

**Comment by archenroot** [comment]
@ergysr - thx for comment, I will check again paper in more detail.
