### ISSUE TITLE
cv.VideoCapture Error

### ISSUE THREAD

**Issue by wangchust** [ergysr/DeepCC#52]
When I compiled mexopencv and run demo, it output this error.
`Error using cv.VideoCapture
Too many input arguments.

Error in DukeVideoReader (line 35)
            obj.Video = cv.VideoCapture(sprintf('%svideos/camera%d/%05d.MTS',obj.DatasetPath,obj.CurrentCamera, obj.CurrentPart), 'API','FFMPEG');

Error in get_opts (line 12)
opts.reader = DukeVideoReader(opts.dataset_path);

Error in demo (line 2)
opts = get_opts();`
My opencv version is 2.4. Is this error caused by opencv version?

**Comment by ergysr** [comment]
Probably yes, the included mexopencv wasn't tested with the 2.4 version.

**Comment by wangchust** [comment]
Thank you for your reply. I'll try opencv 3.3.
