### ISSUE TITLE
triplet_reid Issue

### ISSUE THREAD

**Issue by ahmdtaha** [ergysr/DeepCC#53]
Seems like a redundant call in
[In train.py, line 387](https://github.com/ergysr/DeepCC/blob/ab89f0a82a6b603d87c508b2c3ddc217d7075d6e/src/triplet-reid/train.py#L387)

**dataset = dataset.map(
        lambda  fid, pid: common.fid_to_image(
            fid, pid, image_root=args.image_root,
            image_size=pre_crop_size if args.crop_augment else net_input_size),
        num_parallel_calls=args.loading_threads)**
    # Augment the data if specified by the arguments.
    if args.augment == False:
        **dataset = dataset.map(
            lambda im, fid, pid: common.fid_to_image(
                fid, pid, image_root=args.image_root,
                image_size=pre_crop_size if args.crop_augment else net_input_size),   #Ergys
            num_parallel_calls=args.loading_threads)**

**Comment by ergysr** [comment]
I don't remember the exact reason why I had to modify this, probably it had something to do with the tensorflow version. Is this an actual issue?

**Comment by ahmdtaha** [comment]
You change it to support fancier augmentation techniques like GaussianBlur, ContrastNormalization, etc.

Is this an actual issue? Not an issue, but redundant

**Comment by ergysr** [comment]
Improved augmentation sounds like the right reason for the change. Currently I don't have bandwidth to de-duplicate and verify the code. You're welcome to submit a PR.
