### ISSUE TITLE
compute L0 features

### ISSUE THREAD

**Issue by kingwmk** [ergysr/DeepCC#54]
Hello.
When i want to compute L0 features, i got messages as following:

reading detection 307/1824211
reading detection 308/1824211
[0;36m[h264 @ 0x7fe82c086b80] [0m[1;31mMissing reference picture, default is 0
[0m[0;36m[h264 @ 0x7fe82c086b80] [0m[1;31mdecode_slice_header error
[0m[0;36m[h264 @ 0x7fe82c086b80] [0m[1;31mMissing reference picture, default is 0
[0m[0;36m[h264 @ 0x7fe82c086b80] [0m[1;31mdecode_slice_header error

Did the pictures, used for computing L0 features, are extracted from video? And may i asked what does this error message mean?
Thanks a lot!

**Comment by ergysr** [comment]
@kingwmk Yes, the L0 feature extraction first reads particular video frames, extracts the images, and then computes the features. 

What you report is a warning from the video decoder. During video reading, under the hood there is some additional processing to ensure the image is properly decoded. This is needed as most frames are encoded as P-frames or B-frames. To get a properly decoded frame x, the DukeVideoReader begins reading images sequentially from frame x minus 30 until frame x, to ensure that an I-frame is encountered.

**Comment by kingwmk** [comment]
Hello，will these warnings cause a run error in compute＿L0＿features？@ergysr

**Comment by kingwmk** [comment]
Hi，May i ask that does the motchallenge use all videos of DukeMTMC？

**Comment by ergysr** [comment]
The warnings will not cause an error. 
Motchallenge uses only those parts of the videos that correspond to the test sequences.

**Comment by kingwmk** [comment]
Thanks a lot for your reply  and kindness！The train-val dataset is too big, is there a way we can do a quick experiment on a small sub dataset？

**Comment by ergysr** [comment]
Have you tried [trainval-mini](https://github.com/ergysr/DeepCC/blob/0618544609db62ce1be8a3e9b5693c7c71f5b28f/get_opts.m#L27)?

**Comment by kingwmk** [comment]
yes, thanks. Does it also work in compute＿L0＿features step？

**Comment by kingwmk** [comment]
sequence_window   = opts.sequence_intervals{opts.sequence};
    start_frame       = global2local(opts.start_frames(opts.current_camera), sequence_window(1));
    end_frame         = global2local(opts.start_frames(opts.current_camera), sequence_window(end));

**Comment by kingwmk** [comment]
I have modified the ’ compute＿L0＿features‘ file with the above code. But it runs a bit inefficient and may not use gpu.
