### ISSUE TITLE
Does DeepCC auto learn overlapping footages?

### ISSUE THREAD

**Issue by NicksonYap** [ergysr/DeepCC#56]
Hi

The paper mentions about overlaps where it learns and somehow combines?

Is it implemented in this repo too?

Regards

**Comment by ergysr** [comment]
@NicksonYap The data where this code is evaluated doesn't contain spatially overlapping areas, so this repository sets the correlations to negative infinity for co-occurring detections, for simplicity. 

You can replace the motion model to handle overlapping areas. I had previously done it for some soccer sequences with overlapping views, and for a non-public version of the Duke dataset, by setting correlations to positive if both motion, position, and appearance were similar. For overlapping views the motion model code becomes slightly more complicated, so this repository exposes a relatively simplified version.

**Comment by NicksonYap** [comment]
@ergysr

Nice, it sounds like I just need to replace the negative infinity nunber to a positive number and it should just work?

**Comment by ergysr** [comment]
It depends on your method. If it is very generic, your method would automatically handle disjoint or overlapping areas seamlessly. If it is more specific, you would need to take into account the specific areas of overlap, and handle overlapping and disjoint information separately.

Simply replacing the negative infinity correlation with a positive number will not work out of the box. It can happen that appearances look similar but motion is completely different, in which case a negative correlation makes more sense. 

Essentially you will just need to replace the function which computes correlations to suit your needs.

**Comment by NicksonYap** [comment]
I think I got what you meant!

Basically the indentification part of overlapping footages is fine

However, because of the direction of the camera, (angle of attack, in a way)

There is sort of a X and Y correlation constant that needs to work together across/between overlapping cameras

**Comment by ergysr** [comment]
@NicksonYap Yes, but even more than that, when you have overlapping information, the same person can be seen from several cameras, and this information needs to be fused somehow. When the views are disjoint, the information for a single detection comes only from one camera. If you define a meaningful correlation function, the fusion is done automatically for both cases.

**Comment by NicksonYap** [comment]
Alrite, found the part describing the various matrices
@ergysr It's so well documented, I'm learning a lot!

![screenshot_20190206-074946_drive](https://user-images.githubusercontent.com/5380731/52312025-07b38a80-29e4-11e9-9389-63bef29393de.jpg)

Does L1, L2, L3 mean Level/Layer 1, 2, 3? 

From what I understand:

OpenPose was used to detect a Person, and track the Pixel Coordinates of their feet

The Appearance Model, uses the Weighted Triplet Loss and creates 128 descriptors of a Person (an Appearance) that serves the base data for Re-ID later on (grouping of Appearances as an ID)

The Correlation Clustering by a Binary Integer Program (BIPCC) algorithm performs:
- Grouping of Appearances into a single ID (Re-ID)
- And if not mistaken: Grouping of OpenPose Pixel Coordinates into a Tracklet 

However the BIPCC implemented in this repo does not take into account duplicate Appearances at the same time, which may result in duplicate Tracklets and duplicate IDs

In order to properly implement BIPCC for overlapping footages:
- Appearance Correlation Matrix needs to fuse Appearances that appear at the same time, from different cameras, in overlapping pixel areas
- Motion Prediction Correlation Matrix needs to fuse OpenPose Pixel Coordinates of the same ID that appears in multiple cameras. Which requires mapping the motion due to different camera position and direction.


Please correct me if I'm wrong, even if I used a differen terminology in your papers (to avoid confusion)

**Comment by ergysr** [comment]
@NicksonYap  Tracking computation is done at 4 levels:
L0 computes detections for each frame
L1 computes tracklets (~1 second long)
L2 computes single-camera trajectories
L3 computes multi-camera trajectories

The ReID model is only used to extract appearance descriptors, and a constant velocity motion model is used to compute some motion correlation. These appearance and motion correlations are combined into the final correlation.

Each computation level groups observations from the previous level. For instance L0 takes images and computes detections. L1 takes the L0 detections, computes some features on them (using the reid appearance model and linear prediction motion feature) and runs BIPCC to find groups of detections that should belong to separate people. L2 does the exact same, but groups L1 tracklets into single camera trajectories. This repeats until L3 takes the L2 single camera trajectories and groups them into multi camera trajectories.

You can read the [ACCV 2014 paper](https://users.cs.duke.edu/~tomasi/papers/ristani/ristaniAccv14.pdf) for the basic details. Your interpretation sounds more or less right.
