### ISSUE TITLE
cannot download complete data

### ISSUE THREAD

**Issue by shamoqianting** [ergysr/DeepCC#57]
I tried to download videos of dukemtmc using the matlab script from the website, but I only got about 80GB. Every file seems to be  cut down. Is there any other more stable way to down load the videos ?

**Comment by ergysr** [comment]
Have you tried a manual download from the [website](http://vision.cs.duke.edu/DukeMTMC/data/videos/)? Perhaps your connection is not stable.

**Comment by shamoqianting** [comment]
Thanks for your reply. Manual download can solve this problem.
