### ISSUE TITLE
usb cameras

### ISSUE THREAD

**Issue by hispavista** [ergysr/DeepCC#59]
Hi!
How can I run the demo to detect people in 2 usb cameras? I need to download the entire dataset?
Thank you

**Comment by ergysr** [comment]
If you only want to detect people in 2 usb cameras you can look at [OpenPose](https://github.com/CMU-Perceptual-Computing-Lab/openpose).

**Comment by hispavista** [comment]
But can I track one person accross 2 cameras with OpenPose?

**Comment by hispavista** [comment]
I need to detect a person in a camera and know if it passes through the other camera

**Comment by ergysr** [comment]
You might use OpenPose for detection and this code for tracking, however it will need some work - the goal for this repository was to demo the tracker on the Duke dataset.
