### ISSUE TITLE
DPM/camera1.mat

### ISSUE THREAD

**Issue by ciwei123** [ergysr/DeepCC#60]
@ergysr Hi,thanks for your sharing.Could you tell me how the Detections/DPM/camera1.mat is formed? I download the camera1/00000.MTS, and I want to visualize this vedio using the camera1.mat. But I get two many boxes in the first image, which is the first frame in 00000.MTS vedio?

**Comment by ciwei123** [comment]
@ergysr  36 lines in camera1.mat are the result of the first frame of camera1. But the first frame in 00000.MTS has two people.How to understand this?

**Comment by ergysr** [comment]
Dimensions: http://vision.cs.duke.edu/DukeMTMC/details.html
Visualization: https://github.com/ergysr/DeepCC/blob/master/src/visualization/show_detections.m

**Comment by ciwei123** [comment]
@ergysr I just hava the camera1 vedio, I want to get the four coordinate of every body. What should I do?
