### ISSUE TITLE
using for pedestrian detection

### ISSUE THREAD

**Issue by ciwei123** [ergysr/DeepCC#64]
@ergysr Hi, I want to use the　‘ DukeMTMC datasets’ 　as ‘‘pedestrian detection datasets’’,　Can I use the result of  ''DPM detection result ''  directly as a label? Or, I should use the tracking groundtruth as the label?

**Comment by ciwei123** [comment]
@ergysr I need a detection datasets in surveillane.

**Comment by ergysr** [comment]
The best option is to use the ground truth bounding boxes as the label.

**Comment by ciwei123** [comment]
@ergysr Thanks for your reply. Is the real label recorded when it is completely occluded?　If it is recorded when it is completely occluded, this will affect the model's effect.

**Comment by ergysr** [comment]
There is a label for each frame, whether a person is occluded or not. You may estimate person-person occlusions based on bounding box overlap.

**Comment by ciwei123** [comment]
@ergysr Where I can find the overlap? The camera1 has  10  vedios, how many frames does 00000.MTS have?  Because　the trainRaw.mat  first line is : 
1	1	42178   1329  315	83	210	23.716	82.2852   0.714029 	0.47640
Which picture does 　‘’the 42178 frame‘’　correspond to?

**Comment by ergysr** [comment]
You can go through the readme dedicated to visualization.
