### ISSUE TITLE
Details of the generation of detections and L0_features

### ISSUE THREAD

**Issue by GehenHe** [ergysr/DeepCC#66]
How to generate the detection, _e.g._, camera1.mat, and the L0_features, _e.g._, features1.h5?
Because I want to employ the proposed method on an another dataset, while no details of these modules are provided.

Cheers

**Comment by ergysr** [comment]
To extract detections themselves you should look at openpose.

To extract features from detections you can run https://github.com/ergysr/DeepCC/blob/master/src/compute_L0_features.m

**Comment by GehenHe** [comment]
Thank you for your replies.  Further, what is the format of the detections, since it seems that there are 56 elements of each detection and Openpose provides 25 key point results for each individual. 

What is items and order of the 56 elements of each detection?

Cheers.

**Comment by ergysr** [comment]
The format might have changed recently. Before, body was 18 keypoints if I remember correctly, (x,y,confidence). Here is the code that parses the already computed detections and visualizes them. https://github.com/ergysr/DeepCC/blob/master/src/visualization/show_detections.m

**Comment by GehenHe** [comment]
Thanks a lot.
 : )

**Comment by ttvn** [comment]
> To extract features from detections you can run https://github.com/ergysr/DeepCC/blob/master/src/compute_L0_features.m

Hi @ergysr , 
I tried to extract features again. But, it spent a lot of time to reading detection and the script ran very slow. I'm using RTX 2080Ti. Did you extract all of these features less than 1 days?

**Comment by GehenHe** [comment]
As mentioned by @ergysr, each key point should be (x,y,confidence).
> The format might have changed recently. Before, body was 18 keypoints if I remember correctly, (x,y,confidence). Here is the code that parses the already computed detections and visualizes them. https://github.com/ergysr/DeepCC/blob/master/src/visualization/show_detections.m

However, in the provided detection file, _e.g._, camera1.mat, x,y are in range [0,1], and  which are mismatch with the openpose output format (where x, y are float number that smaller than image width and height). How can I convert the output coordinate of openpose  to the provided detection format?

Cheers

**Comment by ergysr** [comment]
@ttvn Reading all detections can take some time as you are decoding large amounts of video. I can't remember exactly how long it takes, maybe half day per camera, so it's worth doing this in parallel if possible.

@GehenHe The range [0,1] makes the keypoint coordinates resolution independent. You can multiply x and y with 1920 and 1080 accordingly if you are using the original video resolution.
