### ISSUE TITLE
Issue with the demo

### ISSUE THREAD

**Issue by anshulbshah** [ergysr/DeepCC#67]
I am not able to get the demo to work. 

The mexopencv installation was not straightforward in my case (I got an error related to libdc1394.so.22). But using 
`LD_PRELOAD=/opt/local/stow/libdc1394-2.2.5/lib/libdc1394.so.22 matlab` 
I was able to run demo.m for L1_tracklets. But, upon reaching the call to compute_L2_trajectories(opts), I get the following error : 

> Error using fuzzy.internal.utility.validateSigMFParameterValues
Can't load '/opt/common/matlab-r2018a/bin/glnxa64/libmwdastudio.so':
/opt/common/matlab-r2018a/bin/glnxa64/libQt5Network.so.5: undefined symbol:
_Z15qIsEffectiveTLDRK7QString
Error in sigmf (line 30)
fuzzy.internal.utility.validateSigMFParameterValues(params)
Error in getSpaceTimeAffinity (line 57)
indiffMatrix    = 1 - sigmf(timeDifference,[0.1 indifferenceLimit/2]);
Error in solveInGroups (line 42)
    [spacetimeAffinity, impossibilityMatrix, indifferenceMatrix] =
    getSpaceTimeAffinity(tracklets(indices), params.beta, params.speed_limit,
    params.indifference_time);
Error in createTrajectories (line 39)
result = solveInGroups(opts, tracklets(inAssociation),
trackletLabels(inAssociation));
Error in compute_L2_trajectories (line 21)
        trajectories = createTrajectories( opts, trajectories, startFrame,
        endFrame);
Error in demo (line 23)
compute_L2_trajectories(opts);

I also see that I am not able to run `y = sigmf(x = 0:0.1:10,[2 4]);` when I use LD_PRELOAD but without that (Now `y = sigmf(x = 0:0.1:10,[2 4]);`  does not give any errors) I run into the following error  : 

> Invalid MEX-file
'/scratch/DeepCC/src/external/mexopencv/+cv/private/VideoCapture_.mexa64':
libdc1394.so.22: cannot open shared object file: No such file or directory.
Error in cv.VideoCapture (line 182)
            this.id = VideoCapture_(0, 'new');
Error in DukeVideoReader (line 35)
            obj.Video =
   cv.VideoCapture(sprintf('%svideos/camera%d/%05d.MTS',obj.DatasetPath,obj.CurrentCamera,
            obj.CurrentPart), 'API','FFMPEG');
Error in get_opts (line 12)
opts.reader = DukeVideoReader(opts.dataset_path);
Error in demo (line 2)
opts = get_opts();

Further, I am not using mexopencv with opencv-contrib. 
I'd be really grateful for any help!
Thank you!

**Comment by ergysr** [comment]
@anshulbshah I have tested on Linux few times and doing
 `setenv LD_PRELOAD /usr/lib/x86_64-linux-gnu/libstdc++.so.6` 
had solved it for me. You can read more about the issue [here](https://www.mathworks.com/matlabcentral/answers/329796-issue-with-libstdc-so-6). 

Regarding mexopencv, you don't need the contrib module.
