### ISSUE TITLE
Num of frames is different

### ISSUE THREAD

**Issue by wangxiaoyaner** [ergysr/DeepCC#68]
For various reasons, I chose to download videos manually rather than through scripts, and counted the total number of frames in Camera 1 from 00000.MTS to 00009.MTS using opencv, but I found that it was different from the number of frames in Camera on the website. The frame numbers of Seq 0-9 are [38370, 38370, 38660, 48228, 51055, 40964, 57924, 38370, 38876, 16524], totaling 407341 frames, while that of Camera 1 is 359580 frames according to the Time Synchronization section on [http://vision.cs.duke.edu/DukeMTMC/details.html](url). For each video sequence, I use the following code based on python and opencv to count frames 
```
tmp = cv2.VideoCapture(mts)
ret, fram = tmp.read()
fr_n = 0
while ret:
     ret, fram = tmp.read()
     fr_n +=1
````
I'm confused about this, because the exact number of frames is very important.

**Comment by ergysr** [comment]
I don't think it matters how the files are downloaded, as long as the file [checksums](http://vision.cs.duke.edu/DukeMTMC/data/videos/md5sum.txt) match. 

Luckily these issues are already solved for you, and you can take a look at the official video frame reader in [Matlab](https://github.com/ergysr/DeepCC/blob/master/src/duke/DukeVideoReader.m) and [Python](https://github.com/ergysr/DeepCC/blob/master/src/triplet-reid/duke_utils.py).

**Comment by wangxiaoyaner** [comment]
I checked the md5sum and found some errors.  Thank you for your answer. I learned a lot from it!  By the way, the video frame reader in  [Python](https://github.com/ergysr/DeepCC/blob/master/src/triplet-reid/duke_utils.py) does not work because CAP_PROP_FRAME_COUNT in OpenCV is inaccurate according to [this](https://stackoverflow.com/questions/31472155/python-opencv-cv2-cv-cv-cap-prop-frame-count-get-wrong-numbers). I recommend extracting all the video frames first if you handle with Python.

**Comment by wangxiaoyaner** [comment]
> I don't think it matters how the files are downloaded, as long as the file [checksums](http://vision.cs.duke.edu/DukeMTMC/data/videos/md5sum.txt) match.
> 
> Luckily these issues are already solved for you, and you can take a look at the official video frame reader in [Matlab](https://github.com/ergysr/DeepCC/blob/master/src/duke/DukeVideoReader.m) and [Python](https://github.com/ergysr/DeepCC/blob/master/src/triplet-reid/duke_utils.py).
I checked the md5sum and found some errors.  Thank you for your answer. I learned a lot from it!  By the way, the video frame reader in  [Python](https://github.com/ergysr/DeepCC/blob/master/src/triplet-reid/duke_utils.py) does not work because CAP_PROP_FRAME_COUNT in OpenCV is inaccurate according to [this](https://stackoverflow.com/questions/31472155/python-opencv-cv2-cv-cv-cap-prop-frame-count-get-wrong-numbers). I recommend extracting all the video frames first if you handle with Python.

**Comment by wangxiaoyaner** [comment]
I checked the md5sum and found some errors.  Thank you for your answer. I learned a lot from it!  By the way, the video frame reader in  [Python](https://github.com/ergysr/DeepCC/blob/master/src/triplet-reid/duke_utils.py) does not work because CAP_PROP_FRAME_COUNT in OpenCV is inaccurate according to [this](https://stackoverflow.com/questions/31472155/python-opencv-cv2-cv-cv-cap-prop-frame-count-get-wrong-numbers). I recommend extracting all the video frames first if you handle with Python.
