### ISSUE TITLE
the video is about 143GB

### ISSUE THREAD

**Issue by MOONBEAR0703** [ergysr/DeepCC#7]
https://github.com/ergysr/DeepCC/blob/a812ce97e87b8f27bd34fd50cb77acd574946961/src/duke/downloadDukeMTMC.m#L75
I have downloaded the video, the size is about 143GB, not 146GB. But I am not for sure whether I am right.

**Comment by ergysr** [comment]
On a linux machine you can run `md5sum */* > md5sum.txt` in the videos folder and check if the generated file matches [md5sum.txt](http://vision.cs.duke.edu/DukeMTMC/data/videos/md5sum.txt) on the host.

**Comment by MOONBEAR0703** [comment]
@ergysr thanks. I have checked. Mine is not completely right.
