### ISSUE TITLE
Fail to reproduce results on "trainval_mini" subset

### ISSUE THREAD

**Issue by GehenHe** [ergysr/DeepCC#71]
Hi, using the provided codes without any changes and the given detection and appearance feature files, I tried to reproduce the result on "trainval_mini" subset. However, the evaluation produces the following results:

> trainval_mini:
 ********************* Your DukeMTMCT Results *********************
 IDF1  IDP  IDR| Rcll  Prcn   FAR|   GT  MT   PT   ML|    FP    FN   IDs    FM|  MOTA  MOTP MOTAL 
 85.3 85.4 85.1| 93.2  93.5  0.16| 14891363   92   34| 77366 80988   171   454|  86.7  78.5  86.7 
 ********************* Your DukeMTMCT MultiCam Results *********************
IDF1   IDP    IDR
53.01  53.09  52.93 

   where IDF1 score (53.01) is far from close to the reported validation results (IDF1=80.26) in the Table 2 in  "Features for Multi-Target Multi-Camera Tracking and Re-Identificatio".

Note that, Gurobi is successfully installed and correctly configured in these experiments. 

What might be the problem when I try to reproduce the reported result?

**Comment by ergysr** [comment]
I'm not sure what the issue can be. Have you tried with a clean installation of the code?

**Comment by GehenHe** [comment]
Yes, I got this results by using the clean code and only configuring the  _pathes_ in "get_opts.m".
And **Whether the self-trained appearance model in src/triplet-ReID make any difference?**
Since I used the appearance model generated by using the commands:

> mkdir('src/triplet-reid/experiments/')
opts = get_opts();
train_duke(opts);
embed(opts);
evaluation_res_duke_fast(opts);

**Comment by GehenHe** [comment]
Note that, the evaluation result of the appearance model is 

>  mAP = 0.548280, r1 precision = 0.733393

Is this responsible for the decrease on IDF1 score?

**Comment by ergysr** [comment]
The appearance model score looks normal at @73% rank-1 accuracy, so it's likely for some other reason.

**Comment by GehenHe** [comment]
**The problem is that Matlab search path is pointed to some previous copy of the code, where changes are maded in this copy. Therefore even I use the clean installation of the source code, it runs the changed code.**

After delete these path in Matlab search path (type "pathtool" in command window to config), I can finally reproduce the promising results on the validation dataset ("trainval_mini"): 

>  ********************* Your DukeMTMCT Results *********************
 IDF1  IDP  IDR| Rcll  Prcn   FAR|   GT  MT   PT   ML|    FP    FN   IDs    FM|  MOTA  MOTP MOTAL 
 85.4 85.5 85.3| 93.2  93.5  0.16| 14891363   92   34| 77366 80988   132   454|  86.7  78.5  86.7 
 ********************* Your DukeMTMCT MultiCam Results *********************
IDF1   IDP    IDR
79.15  79.27  79.03

Thank @ergysr  for  the  kindly help.
Cheers : )
